/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_acceuil (void);
GtkWidget* create_gestion_Capteur (void);
GtkWidget* create_capteurs_defectueux (void);
GtkWidget* create_etages_contenant_des_pannes (void);
GtkWidget* create_liste_des_alarmes (void);
