/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_acceuil (void)
{
  GtkWidget *acceuil;
  GtkWidget *fixed1;
  GtkWidget *button_capteurs_defectueux;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image27;
  GtkWidget *label102;
  GtkWidget *button_pannes;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image26;
  GtkWidget *label101;
  GtkWidget *button_alarmes;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image25;
  GtkWidget *label100;
  GtkWidget *button2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *image40;

  acceuil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (acceuil, 1000, 700);
  gtk_window_set_title (GTK_WINDOW (acceuil), _("acceuil"));
  gtk_window_set_position (GTK_WINDOW (acceuil), GTK_WIN_POS_CENTER);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (acceuil), fixed1);

  button_capteurs_defectueux = gtk_button_new ();
  gtk_widget_show (button_capteurs_defectueux);
  gtk_fixed_put (GTK_FIXED (fixed1), button_capteurs_defectueux, 768, 312);
  gtk_widget_set_size_request (button_capteurs_defectueux, 176, 72);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (button_capteurs_defectueux), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image27 = gtk_image_new_from_stock ("gtk-undelete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox26), image27, FALSE, FALSE, 0);

  label102 = gtk_label_new_with_mnemonic (_("   Les capteurs\n     d\303\251fectueux"));
  gtk_widget_show (label102);
  gtk_box_pack_start (GTK_BOX (hbox26), label102, FALSE, FALSE, 0);

  button_pannes = gtk_button_new ();
  gtk_widget_show (button_pannes);
  gtk_fixed_put (GTK_FIXED (fixed1), button_pannes, 768, 432);
  gtk_widget_set_size_request (button_pannes, 176, 72);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (button_pannes), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image26 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox25), image26, FALSE, FALSE, 0);

  label101 = gtk_label_new_with_mnemonic (_(" Les \303\251tages contenant\n           des pannes"));
  gtk_widget_show (label101);
  gtk_box_pack_start (GTK_BOX (hbox25), label101, FALSE, FALSE, 0);

  button_alarmes = gtk_button_new ();
  gtk_widget_show (button_alarmes);
  gtk_fixed_put (GTK_FIXED (fixed1), button_alarmes, 768, 552);
  gtk_widget_set_size_request (button_alarmes, 176, 72);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (button_alarmes), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image25 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox24), image25, FALSE, FALSE, 0);

  label100 = gtk_label_new_with_mnemonic (_(" La liste des alarmes"));
  gtk_widget_show (label100);
  gtk_box_pack_start (GTK_BOX (hbox24), label100, FALSE, FALSE, 0);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 768, 192);
  gtk_widget_set_size_request (button2, 176, 72);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_(" Gestion Capteurs"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  image40 = create_pixmap (acceuil, "voilé.jpg");
  gtk_widget_show (image40);
  gtk_fixed_put (GTK_FIXED (fixed1), image40, 80, 0);
  gtk_widget_set_size_request (image40, 624, 728);

  g_signal_connect ((gpointer) button_capteurs_defectueux, "clicked",
                    G_CALLBACK (on_button_capteurs_defectueux_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_pannes, "clicked",
                    G_CALLBACK (on_button_pannes_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_alarmes, "clicked",
                    G_CALLBACK (on_button_alarmes_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (acceuil, acceuil, "acceuil");
  GLADE_HOOKUP_OBJECT (acceuil, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (acceuil, button_capteurs_defectueux, "button_capteurs_defectueux");
  GLADE_HOOKUP_OBJECT (acceuil, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (acceuil, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (acceuil, image27, "image27");
  GLADE_HOOKUP_OBJECT (acceuil, label102, "label102");
  GLADE_HOOKUP_OBJECT (acceuil, button_pannes, "button_pannes");
  GLADE_HOOKUP_OBJECT (acceuil, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (acceuil, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (acceuil, image26, "image26");
  GLADE_HOOKUP_OBJECT (acceuil, label101, "label101");
  GLADE_HOOKUP_OBJECT (acceuil, button_alarmes, "button_alarmes");
  GLADE_HOOKUP_OBJECT (acceuil, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (acceuil, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (acceuil, image25, "image25");
  GLADE_HOOKUP_OBJECT (acceuil, label100, "label100");
  GLADE_HOOKUP_OBJECT (acceuil, button2, "button2");
  GLADE_HOOKUP_OBJECT (acceuil, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (acceuil, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (acceuil, image2, "image2");
  GLADE_HOOKUP_OBJECT (acceuil, label2, "label2");
  GLADE_HOOKUP_OBJECT (acceuil, image40, "image40");

  return acceuil;
}

GtkWidget*
create_gestion_Capteur (void)
{
  GtkWidget *gestion_Capteur;
  GtkWidget *fixed2;
  GtkWidget *button4;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label4;
  GtkWidget *button3;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *notebook1;
  GtkWidget *fixed3;
  GtkWidget *entry1;
  GtkWidget *calendar1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *combobox1;
  GtkWidget *label14;
  GtkWidget *label116;
  GtkWidget *label111;
  GtkWidget *label113;
  GtkWidget *label112;
  GtkWidget *checkbutton1;
  GtkWidget *checkbutton2;
  GtkWidget *checkbutton3;
  GtkWidget *button5;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label7;
  GtkWidget *image35;
  GtkWidget *label9;
  GtkWidget *label109;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *radiobutton3;
  GtkWidget *radiobutton4;
  GtkWidget *label110;
  GtkWidget *label8;
  GtkWidget *label15;
  GtkWidget *label127;
  GtkWidget *label114;
  GtkWidget *label128;
  GtkWidget *fixed4;
  GtkWidget *entry2;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;
  GtkWidget *button6;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label22;
  GtkWidget *entry12;
  GtkWidget *combobox2;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkObject *spinbutton8_adj;
  GtkWidget *spinbutton8;
  GtkWidget *entry13;
  GtkWidget *label118;
  GtkWidget *label119;
  GtkWidget *label123;
  GtkWidget *label124;
  GtkWidget *label122;
  GtkWidget *label125;
  GtkWidget *button7;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label23;
  GtkWidget *label25;
  GtkWidget *label117;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *label121;
  GtkWidget *label129;
  GtkWidget *fixed8;
  GtkWidget *entry7;
  GtkWidget *image39;
  GtkWidget *button13;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label67;
  GtkWidget *label126;
  GtkWidget *label65;
  GtkWidget *label66;
  GtkWidget *scrolledwindow3;
  GtkWidget *treeview3;
  GtkWidget *label130;

  gestion_Capteur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (gestion_Capteur, 1000, 700);
  gtk_window_set_title (GTK_WINDOW (gestion_Capteur), _("Gestion Cpteur"));
  gtk_window_set_position (GTK_WINDOW (gestion_Capteur), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (gestion_Capteur), FALSE);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (gestion_Capteur), fixed2);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4, 888, 648);
  gtk_widget_set_size_request (button4, 96, 53);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button4), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3, 16, 648);
  gtk_widget_set_size_request (button3, 96, 53);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed2), notebook1, 0, 8);
  gtk_widget_set_size_request (notebook1, 1016, 640);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed3), entry1, 176, 104);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed3), calendar1, 344, 280);
  gtk_widget_set_size_request (calendar1, 226, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 3, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton2, 128, 288);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  spinbutton5_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton5, 128, 336);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  spinbutton6_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton6, 128, 392);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox1, 176, 152);
  gtk_widget_set_size_request (combobox1, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Temperature"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Debit"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Fumee"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Dechets"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Mouvement"));

  label14 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Type :</b></span>"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed3), label14, 8, 144);
  gtk_widget_set_size_request (label14, 128, 48);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);

  label116 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Constructeur:</b></span>"));
  gtk_widget_show (label116);
  gtk_fixed_put (GTK_FIXED (fixed3), label116, 24, 208);
  gtk_widget_set_size_request (label116, 104, 24);
  gtk_label_set_use_markup (GTK_LABEL (label116), TRUE);

  label111 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Etage :</b></span>"));
  gtk_widget_show (label111);
  gtk_fixed_put (GTK_FIXED (fixed3), label111, 40, 288);
  gtk_widget_set_size_request (label111, 72, 24);
  gtk_label_set_use_markup (GTK_LABEL (label111), TRUE);

  label113 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Val Max:</b></span>"));
  gtk_widget_show (label113);
  gtk_fixed_put (GTK_FIXED (fixed3), label113, 24, 336);
  gtk_widget_set_size_request (label113, 97, 24);
  gtk_label_set_use_markup (GTK_LABEL (label113), TRUE);

  label112 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Bloc :</b></span>"));
  gtk_widget_show (label112);
  gtk_fixed_put (GTK_FIXED (fixed3), label112, 40, 480);
  gtk_widget_set_size_request (label112, 64, 24);
  gtk_label_set_use_markup (GTK_LABEL (label112), TRUE);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("A"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton1, 104, 480);
  gtk_widget_set_size_request (checkbutton1, 48, 24);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("B"));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton2, 152, 480);
  gtk_widget_set_size_request (checkbutton2, 56, 24);

  checkbutton3 = gtk_check_button_new_with_mnemonic (_("C"));
  gtk_widget_show (checkbutton3);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton3, 208, 480);
  gtk_widget_set_size_request (checkbutton3, 56, 24);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed3), button5, 368, 528);
  gtk_widget_set_size_request (button5, 96, 53);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button5), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox5), label7, FALSE, FALSE, 0);

  image35 = create_pixmap (gestion_Capteur, "Logo_ESPRIT_-_Tunisie (1).png");
  gtk_widget_show (image35);
  gtk_fixed_put (GTK_FIXED (fixed3), image35, 480, 0);
  gtk_widget_set_size_request (image35, 528, 336);

  label9 = gtk_label_new (_("<span foreground=\"red\"><b>Saisir REF !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label9, 264, 80);
  gtk_widget_set_size_request (label9, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label9), TRUE);

  label109 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Reference Capteur :</b></span>"));
  gtk_widget_show (label109);
  gtk_fixed_put (GTK_FIXED (fixed3), label109, 0, 96);
  gtk_widget_set_size_request (label109, 176, 40);
  gtk_label_set_use_markup (GTK_LABEL (label109), TRUE);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Hitech"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton1, 160, 208);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("ABB Automation"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton2, 280, 208);
  gtk_widget_set_size_request (radiobutton2, 145, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("NEXT"));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton3, 160, 240);
  gtk_widget_set_size_request (radiobutton3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("TOMRA"));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton4, 280, 240);
  gtk_widget_set_size_request (radiobutton4, 152, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  label110 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>date d'ajout :</b></span>"));
  gtk_widget_show (label110);
  gtk_fixed_put (GTK_FIXED (fixed3), label110, 208, 352);
  gtk_widget_set_size_request (label110, 128, 48);
  gtk_label_set_use_markup (GTK_LABEL (label110), TRUE);

  label8 = gtk_label_new_with_mnemonic (_("<span foreground=\"green\"><b>Capteur existant</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label8, 440, 520);
  gtk_widget_set_size_request (label8, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label8), TRUE);

  label15 = gtk_label_new (_("<span foreground=\"red\"><b>Choisir type de capteur !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 304, 136);
  gtk_widget_set_size_request (label15, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  label127 = gtk_label_new_with_mnemonic (_("<span foreground=\"green\"><b>Capteur ajout\303\251 avec succ\303\251s</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label127, 112, 24);
  gtk_widget_set_size_request (label127, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label127), TRUE);

  label114 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Val Min:</b></span>"));
  gtk_widget_show (label114);
  gtk_fixed_put (GTK_FIXED (fixed3), label114, 32, 392);
  gtk_widget_set_size_request (label114, 89, 24);
  gtk_label_set_use_markup (GTK_LABEL (label114), TRUE);

  label128 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Ajouter</b></span>"));
  gtk_widget_show (label128);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label128);
  gtk_widget_set_size_request (label128, 100, 40);
  gtk_label_set_use_markup (GTK_LABEL (label128), TRUE);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed4), entry2, 792, 272);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  spinbutton4_adj = gtk_adjustment_new (1, 1, 3, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton4, 832, 432);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed4), scrolledwindow1, 0, 88);
  gtk_widget_set_size_request (scrolledwindow1, 584, 384);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);
  gtk_widget_set_size_request (treeview1, 584, 384);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed4), button6, 208, 512);
  gtk_widget_set_size_request (button6, 104, 56);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button6), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox6), label22, FALSE, FALSE, 0);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed4), entry12, 792, 208);
  gtk_widget_set_size_request (entry12, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox2, 792, 160);
  gtk_widget_set_size_request (combobox2, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Temperature"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Debit"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Fumee"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Dechets"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Mouvement"));

  spinbutton7_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_show (spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton7, 832, 352);
  gtk_widget_set_size_request (spinbutton7, 60, 27);

  spinbutton8_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton8 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton8_adj), 1, 0);
  gtk_widget_show (spinbutton8);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton8, 832, 392);
  gtk_widget_set_size_request (spinbutton8, 60, 27);

  entry13 = gtk_entry_new ();
  gtk_widget_show (entry13);
  gtk_fixed_put (GTK_FIXED (fixed4), entry13, 832, 480);
  gtk_widget_set_size_request (entry13, 64, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 8226);

  label118 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Type de capteur :</b></span>"));
  gtk_widget_show (label118);
  gtk_fixed_put (GTK_FIXED (fixed4), label118, 648, 152);
  gtk_widget_set_size_request (label118, 128, 48);
  gtk_label_set_use_markup (GTK_LABEL (label118), TRUE);

  label119 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Constructeur :</b></span>"));
  gtk_widget_show (label119);
  gtk_fixed_put (GTK_FIXED (fixed4), label119, 672, 208);
  gtk_widget_set_size_request (label119, 105, 32);
  gtk_label_set_use_markup (GTK_LABEL (label119), TRUE);

  label123 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Val Min :</b></span>"));
  gtk_widget_show (label123);
  gtk_fixed_put (GTK_FIXED (fixed4), label123, 696, 400);
  gtk_widget_set_size_request (label123, 81, 16);
  gtk_label_set_use_markup (GTK_LABEL (label123), TRUE);

  label124 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Etage :</b></span>"));
  gtk_widget_show (label124);
  gtk_fixed_put (GTK_FIXED (fixed4), label124, 680, 416);
  gtk_widget_set_size_request (label124, 128, 48);
  gtk_label_set_use_markup (GTK_LABEL (label124), TRUE);

  label122 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Val Max :</b></span>"));
  gtk_widget_show (label122);
  gtk_fixed_put (GTK_FIXED (fixed4), label122, 696, 360);
  gtk_widget_set_size_request (label122, 72, 24);
  gtk_label_set_use_markup (GTK_LABEL (label122), TRUE);

  label125 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Bloc :</b></span>"));
  gtk_widget_show (label125);
  gtk_fixed_put (GTK_FIXED (fixed4), label125, 720, 480);
  gtk_widget_set_size_request (label125, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label125), TRUE);

  button7 = gtk_button_new ();
  gtk_fixed_put (GTK_FIXED (fixed4), button7, 808, 520);
  gtk_widget_set_size_request (button7, 96, 53);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button7), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox7), label23, FALSE, FALSE, 0);

  label25 = gtk_label_new ("");
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed4), label25, 808, 96);
  gtk_widget_set_size_request (label25, 104, 48);

  label117 = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Modifier le capteur :</b></span>"));
  gtk_widget_show (label117);
  gtk_fixed_put (GTK_FIXED (fixed4), label117, 632, 96);
  gtk_widget_set_size_request (label117, 152, 48);
  gtk_label_set_use_markup (GTK_LABEL (label117), TRUE);

  label26 = gtk_label_new (_("<span foreground=\"green\"><i>Capteur modifi\303\251 avec succ\303\251s</i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label26, 696, 24);
  gtk_widget_set_size_request (label26, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  label27 = gtk_label_new (_("<span foreground=\"red\"><b>Selectionner un capteur!</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label27, 104, 24);
  gtk_widget_set_size_request (label27, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label27), TRUE);

  label121 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Date d'ajout :</b></span>"));
  gtk_widget_show (label121);
  gtk_fixed_put (GTK_FIXED (fixed4), label121, 664, 264);
  gtk_widget_set_size_request (label121, 128, 48);
  gtk_label_set_use_markup (GTK_LABEL (label121), TRUE);

  label129 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Afficher/Modifier/Supprimer</b></span>"));
  gtk_widget_show (label129);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label129);
  gtk_widget_set_size_request (label129, 210, 40);
  gtk_label_set_use_markup (GTK_LABEL (label129), TRUE);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed8);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed8), entry7, 632, 392);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  image39 = create_pixmap (gestion_Capteur, "chercher.jpg");
  gtk_widget_show (image39);
  gtk_fixed_put (GTK_FIXED (fixed8), image39, 528, 40);
  gtk_widget_set_size_request (image39, 464, 296);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed8), button13, 840, 376);
  gtk_widget_set_size_request (button13, 96, 53);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button13), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label67 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label67);
  gtk_box_pack_start (GTK_BOX (hbox13), label67, FALSE, FALSE, 0);

  label126 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b> Type :</b></span>"));
  gtk_widget_show (label126);
  gtk_fixed_put (GTK_FIXED (fixed8), label126, 528, 384);
  gtk_widget_set_size_request (label126, 128, 48);
  gtk_label_set_use_markup (GTK_LABEL (label126), TRUE);

  label65 = gtk_label_new (_("<span foreground=\"green\"><b>Capteur (s) existe (s)</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed8), label65, 608, 456);
  gtk_widget_set_size_request (label65, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label65), TRUE);

  label66 = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed8), label66, 696, 504);
  gtk_widget_set_size_request (label66, 72, 56);
  gtk_label_set_use_markup (GTK_LABEL (label66), TRUE);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_fixed_put (GTK_FIXED (fixed8), scrolledwindow3, 0, 0);
  gtk_widget_set_size_request (scrolledwindow3, 552, 584);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), treeview3);
  gtk_widget_set_size_request (treeview3, 592, 344);

  label130 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Chercher</b></span>"));
  gtk_widget_show (label130);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label130);
  gtk_widget_set_size_request (label130, 96, 40);
  gtk_label_set_use_markup (GTK_LABEL (label130), TRUE);

  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2, "toggled",
                    G_CALLBACK (on_checkbutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton3, "toggled",
                    G_CALLBACK (on_checkbutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_AjouterCapteur_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3, "toggled",
                    G_CALLBACK (on_radiobutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton4, "toggled",
                    G_CALLBACK (on_radiobutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_SupprimerCapteur_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_ModifierCapteur_clicked),
                    NULL);
  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (on_chercherCapteur_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label116), spinbutton5);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label111), spinbutton2);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label113), spinbutton5);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label112), checkbutton1);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label114), spinbutton5);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label118), spinbutton5);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label119), spinbutton5);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label123), spinbutton5);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label124), spinbutton5);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label122), spinbutton5);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label125), spinbutton5);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label117), spinbutton5);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label121), spinbutton5);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label126), spinbutton5);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_Capteur, gestion_Capteur, "gestion_Capteur");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, button4, "button4");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, image4, "image4");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label4, "label4");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, button3, "button3");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, image3, "image3");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label3, "label3");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label14, "label14");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label116, "label116");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label111, "label111");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label113, "label113");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label112, "label112");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, checkbutton3, "checkbutton3");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, button5, "button5");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, image5, "image5");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label7, "label7");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, image35, "image35");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label9, "label9");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label109, "label109");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label110, "label110");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label8, "label8");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label15, "label15");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label127, "label127");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label114, "label114");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label128, "label128");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, button6, "button6");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, image6, "image6");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label22, "label22");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, spinbutton7, "spinbutton7");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, spinbutton8, "spinbutton8");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label118, "label118");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label119, "label119");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label123, "label123");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label124, "label124");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label122, "label122");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label125, "label125");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, button7, "button7");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, image7, "image7");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label23, "label23");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label25, "label25");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label117, "label117");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label26, "label26");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label27, "label27");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label121, "label121");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label129, "label129");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, image39, "image39");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, button13, "button13");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, image13, "image13");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label67, "label67");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label126, "label126");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label65, "label65");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label66, "label66");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (gestion_Capteur, label130, "label130");

  return gestion_Capteur;
}

GtkWidget*
create_capteurs_defectueux (void)
{
  GtkWidget *capteurs_defectueux;
  GtkWidget *fixed11;
  GtkWidget *image37;
  GtkWidget *button_capteurDef_acceuil;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *image28;
  GtkWidget *label103;
  GtkWidget *button28;
  GtkWidget *alignment28;
  GtkWidget *hbox28;
  GtkWidget *image29;
  GtkWidget *label104;
  GtkWidget *scrolledwindow7;
  GtkWidget *treeview7;
  GtkWidget *image38;

  capteurs_defectueux = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (capteurs_defectueux), _("Les capteurs d\303\251fectueux"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (capteurs_defectueux), fixed11);

  image37 = create_pixmap (capteurs_defectueux, NULL);
  gtk_widget_show (image37);
  gtk_fixed_put (GTK_FIXED (fixed11), image37, 136, 112);
  gtk_widget_set_size_request (image37, 21, 21);

  button_capteurDef_acceuil = gtk_button_new ();
  gtk_widget_show (button_capteurDef_acceuil);
  gtk_fixed_put (GTK_FIXED (fixed11), button_capteurDef_acceuil, 24, 720);
  gtk_widget_set_size_request (button_capteurDef_acceuil, 88, 45);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (button_capteurDef_acceuil), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  image28 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox27), image28, FALSE, FALSE, 0);

  label103 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label103);
  gtk_box_pack_start (GTK_BOX (hbox27), label103, FALSE, FALSE, 0);

  button28 = gtk_button_new ();
  gtk_widget_show (button28);
  gtk_fixed_put (GTK_FIXED (fixed11), button28, 944, 720);
  gtk_widget_set_size_request (button28, 88, 48);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (button28), alignment28);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox28);

  image29 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox28), image29, FALSE, FALSE, 0);

  label104 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label104);
  gtk_box_pack_start (GTK_BOX (hbox28), label104, FALSE, FALSE, 0);

  scrolledwindow7 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow7);
  gtk_fixed_put (GTK_FIXED (fixed11), scrolledwindow7, 96, 16);
  gtk_widget_set_size_request (scrolledwindow7, 464, 528);

  treeview7 = gtk_tree_view_new ();
  gtk_widget_show (treeview7);
  gtk_container_add (GTK_CONTAINER (scrolledwindow7), treeview7);

  image38 = create_pixmap (capteurs_defectueux, "equipement_def.jpg");
  gtk_widget_show (image38);
  gtk_fixed_put (GTK_FIXED (fixed11), image38, 0, 0);
  gtk_widget_set_size_request (image38, 1056, 696);

  g_signal_connect ((gpointer) button_capteurDef_acceuil, "clicked",
                    G_CALLBACK (on_button_capteurDef_acceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) button28, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (capteurs_defectueux, capteurs_defectueux, "capteurs_defectueux");
  GLADE_HOOKUP_OBJECT (capteurs_defectueux, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (capteurs_defectueux, image37, "image37");
  GLADE_HOOKUP_OBJECT (capteurs_defectueux, button_capteurDef_acceuil, "button_capteurDef_acceuil");
  GLADE_HOOKUP_OBJECT (capteurs_defectueux, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (capteurs_defectueux, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (capteurs_defectueux, image28, "image28");
  GLADE_HOOKUP_OBJECT (capteurs_defectueux, label103, "label103");
  GLADE_HOOKUP_OBJECT (capteurs_defectueux, button28, "button28");
  GLADE_HOOKUP_OBJECT (capteurs_defectueux, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (capteurs_defectueux, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (capteurs_defectueux, image29, "image29");
  GLADE_HOOKUP_OBJECT (capteurs_defectueux, label104, "label104");
  GLADE_HOOKUP_OBJECT (capteurs_defectueux, scrolledwindow7, "scrolledwindow7");
  GLADE_HOOKUP_OBJECT (capteurs_defectueux, treeview7, "treeview7");
  GLADE_HOOKUP_OBJECT (capteurs_defectueux, image38, "image38");

  return capteurs_defectueux;
}

GtkWidget*
create_etages_contenant_des_pannes (void)
{
  GtkWidget *etages_contenant_des_pannes;
  GtkWidget *fixed12;
  GtkWidget *button_etagePanne_acceuil;
  GtkWidget *alignment30;
  GtkWidget *hbox30;
  GtkWidget *image31;
  GtkWidget *label106;
  GtkWidget *button29;
  GtkWidget *alignment29;
  GtkWidget *hbox29;
  GtkWidget *image30;
  GtkWidget *label105;
  GtkWidget *scrolledwindow8;
  GtkWidget *treeview8;
  GtkWidget *image36;

  etages_contenant_des_pannes = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (etages_contenant_des_pannes), _("Les \303\251tages contenant des pannes"));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (etages_contenant_des_pannes), fixed12);

  button_etagePanne_acceuil = gtk_button_new ();
  gtk_widget_show (button_etagePanne_acceuil);
  gtk_fixed_put (GTK_FIXED (fixed12), button_etagePanne_acceuil, 24, 560);
  gtk_widget_set_size_request (button_etagePanne_acceuil, 96, 53);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (button_etagePanne_acceuil), alignment30);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox30);

  image31 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_box_pack_start (GTK_BOX (hbox30), image31, FALSE, FALSE, 0);

  label106 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label106);
  gtk_box_pack_start (GTK_BOX (hbox30), label106, FALSE, FALSE, 0);

  button29 = gtk_button_new ();
  gtk_widget_show (button29);
  gtk_fixed_put (GTK_FIXED (fixed12), button29, 944, 560);
  gtk_widget_set_size_request (button29, 96, 53);

  alignment29 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (button29), alignment29);

  hbox29 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox29);
  gtk_container_add (GTK_CONTAINER (alignment29), hbox29);

  image30 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox29), image30, FALSE, FALSE, 0);

  label105 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label105);
  gtk_box_pack_start (GTK_BOX (hbox29), label105, FALSE, FALSE, 0);

  scrolledwindow8 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow8);
  gtk_fixed_put (GTK_FIXED (fixed12), scrolledwindow8, 64, 48);
  gtk_widget_set_size_request (scrolledwindow8, 424, 496);

  treeview8 = gtk_tree_view_new ();
  gtk_widget_show (treeview8);
  gtk_container_add (GTK_CONTAINER (scrolledwindow8), treeview8);

  image36 = create_pixmap (etages_contenant_des_pannes, "panne.jpg");
  gtk_widget_show (image36);
  gtk_fixed_put (GTK_FIXED (fixed12), image36, 520, 0);
  gtk_widget_set_size_request (image36, 560, 536);

  g_signal_connect ((gpointer) button_etagePanne_acceuil, "clicked",
                    G_CALLBACK (on_button_etagePanne_acceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) button29, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (etages_contenant_des_pannes, etages_contenant_des_pannes, "etages_contenant_des_pannes");
  GLADE_HOOKUP_OBJECT (etages_contenant_des_pannes, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (etages_contenant_des_pannes, button_etagePanne_acceuil, "button_etagePanne_acceuil");
  GLADE_HOOKUP_OBJECT (etages_contenant_des_pannes, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (etages_contenant_des_pannes, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (etages_contenant_des_pannes, image31, "image31");
  GLADE_HOOKUP_OBJECT (etages_contenant_des_pannes, label106, "label106");
  GLADE_HOOKUP_OBJECT (etages_contenant_des_pannes, button29, "button29");
  GLADE_HOOKUP_OBJECT (etages_contenant_des_pannes, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (etages_contenant_des_pannes, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (etages_contenant_des_pannes, image30, "image30");
  GLADE_HOOKUP_OBJECT (etages_contenant_des_pannes, label105, "label105");
  GLADE_HOOKUP_OBJECT (etages_contenant_des_pannes, scrolledwindow8, "scrolledwindow8");
  GLADE_HOOKUP_OBJECT (etages_contenant_des_pannes, treeview8, "treeview8");
  GLADE_HOOKUP_OBJECT (etages_contenant_des_pannes, image36, "image36");

  return etages_contenant_des_pannes;
}

GtkWidget*
create_liste_des_alarmes (void)
{
  GtkWidget *liste_des_alarmes;
  GtkWidget *fixed13;
  GtkWidget *image41;
  GtkWidget *scrolledwindow9;
  GtkWidget *treeview9;
  GtkWidget *button_alarmes_acceuil;
  GtkWidget *alignment31;
  GtkWidget *hbox31;
  GtkWidget *image32;
  GtkWidget *label107;
  GtkWidget *button32;
  GtkWidget *alignment32;
  GtkWidget *hbox32;
  GtkWidget *image33;
  GtkWidget *label108;

  liste_des_alarmes = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (liste_des_alarmes), _("La liste des alarmes"));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (liste_des_alarmes), fixed13);

  image41 = create_pixmap (liste_des_alarmes, "cap.jpg");
  gtk_widget_show (image41);
  gtk_fixed_put (GTK_FIXED (fixed13), image41, 0, 0);
  gtk_widget_set_size_request (image41, 456, 696);

  scrolledwindow9 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow9);
  gtk_fixed_put (GTK_FIXED (fixed13), scrolledwindow9, 472, 0);
  gtk_widget_set_size_request (scrolledwindow9, 280, 416);

  treeview9 = gtk_tree_view_new ();
  gtk_widget_show (treeview9);
  gtk_container_add (GTK_CONTAINER (scrolledwindow9), treeview9);

  button_alarmes_acceuil = gtk_button_new ();
  gtk_widget_show (button_alarmes_acceuil);
  gtk_fixed_put (GTK_FIXED (fixed13), button_alarmes_acceuil, 648, 536);
  gtk_widget_set_size_request (button_alarmes_acceuil, 96, 53);

  alignment31 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment31);
  gtk_container_add (GTK_CONTAINER (button_alarmes_acceuil), alignment31);

  hbox31 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox31);
  gtk_container_add (GTK_CONTAINER (alignment31), hbox31);

  image32 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_box_pack_start (GTK_BOX (hbox31), image32, FALSE, FALSE, 0);

  label107 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label107);
  gtk_box_pack_start (GTK_BOX (hbox31), label107, FALSE, FALSE, 0);

  button32 = gtk_button_new ();
  gtk_widget_show (button32);
  gtk_fixed_put (GTK_FIXED (fixed13), button32, 496, 536);
  gtk_widget_set_size_request (button32, 96, 53);

  alignment32 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment32);
  gtk_container_add (GTK_CONTAINER (button32), alignment32);

  hbox32 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox32);
  gtk_container_add (GTK_CONTAINER (alignment32), hbox32);

  image33 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image33);
  gtk_box_pack_start (GTK_BOX (hbox32), image33, FALSE, FALSE, 0);

  label108 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label108);
  gtk_box_pack_start (GTK_BOX (hbox32), label108, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_alarmes_acceuil, "clicked",
                    G_CALLBACK (on_button_alarmes_acceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) button32, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (liste_des_alarmes, liste_des_alarmes, "liste_des_alarmes");
  GLADE_HOOKUP_OBJECT (liste_des_alarmes, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (liste_des_alarmes, image41, "image41");
  GLADE_HOOKUP_OBJECT (liste_des_alarmes, scrolledwindow9, "scrolledwindow9");
  GLADE_HOOKUP_OBJECT (liste_des_alarmes, treeview9, "treeview9");
  GLADE_HOOKUP_OBJECT (liste_des_alarmes, button_alarmes_acceuil, "button_alarmes_acceuil");
  GLADE_HOOKUP_OBJECT (liste_des_alarmes, alignment31, "alignment31");
  GLADE_HOOKUP_OBJECT (liste_des_alarmes, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (liste_des_alarmes, image32, "image32");
  GLADE_HOOKUP_OBJECT (liste_des_alarmes, label107, "label107");
  GLADE_HOOKUP_OBJECT (liste_des_alarmes, button32, "button32");
  GLADE_HOOKUP_OBJECT (liste_des_alarmes, alignment32, "alignment32");
  GLADE_HOOKUP_OBJECT (liste_des_alarmes, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (liste_des_alarmes, image33, "image33");
  GLADE_HOOKUP_OBJECT (liste_des_alarmes, label108, "label108");

  return liste_des_alarmes;
}

