/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_LOGIN (void);
GtkWidget* create_ADMIN (void);
GtkWidget* create_AJOUT (void);
GtkWidget* create_SUPP (void);
GtkWidget* create_RECHERCHE (void);
GtkWidget* create_MODIF (void);
GtkWidget* create_first (void);
GtkWidget* create_ajout (void);
GtkWidget* create_modifier (void);
GtkWidget* create_sup (void);
GtkWidget* create_affichage (void);
GtkWidget* create_GestionFoyer (void);
GtkWidget* create_dashboard (void);
GtkWidget* create_mod (void);
GtkWidget* create_af (void);
GtkWidget* create_aj (void);
GtkWidget* create_acceuil (void);
GtkWidget* create_gestion_Capteur (void);
GtkWidget* create_capteurs_defectueux (void);
GtkWidget* create_etages_contenant_des_pannes (void);
GtkWidget* create_liste_des_alarmes (void);
GtkWidget* create_dash (void);
GtkWidget* create_afiicher_st (void);
GtkWidget* create_ajouter_st (void);
GtkWidget* create_supprimer_st (void);
GtkWidget* create_modifier_st (void);
GtkWidget* create_window1 (void);
